spring:
  data:
    mongodb:
      username: mgkadmin
      password: mgkadmin
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8091